### ISSUE TITLE
Asus FX506IV: Fan starts working after few seconds of turning off

### ISSUE THREAD

**Issue by CyberAndrew** [Karmel0x/AsusFanControl#5]
If I turn off fans, after few seconds they start to continue working as usual.
It doesn't override fan control when I set it to off. Only for few seconds.

It will be very useful to force silence when I have weak load like browsing, movies etc.

**Comment by CyberAndrew** [comment]
The problem doesn't appears on command line version of program. Only in GUI.

**Comment by Karmel0x** [comment]
there is no "turn off fans" function
when you uncheck the `turn on` checkbox, it disables the fan test mode, which seems to trigger a reset of the fan state, which is why it looks like the fan has been turned off for a few seconds

anyway, you should achieve what you need in latest commit using option mentioned in #3
